/* eslint-disable @typescript-eslint/no-require-imports -- Installed Node test loader. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const basis={membershipId:id(2),legalEntityId:id(3),profileRevisions:['local-driver-cash.v1'],warehouseIds:[id(4)],kinds:['service_charge']},input={...basis,expectedAcceptanceId:null,reason:'Synthetic exact supplement'};
function compile(file,loader){const m=new Module(file,module);m.paths=module.paths;if(loader)m.require=loader;m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function load(){const state={context:'A',epoch:1,data:null,calls:[]};return {...compile(path.join(__dirname,'../lib/cash-administration.ts'),p=>p==='./api'?{api:{get:async(...v)=>{state.calls.push(v);return{data:state.wait?await state.wait:state.data}}}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?compile(path.join(__dirname,'../lib/creation-intent.ts')):require(p)),state};}
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id(1),lock:async f=>f(),calls:[],send:async i=>{assert.equal(JSON.parse(raw).operationId,i.operationId);d.calls.push(i);return{proposalId:i.operationId,fingerprint:'a'.repeat(64)}}};return d;}
test('exact singleton profiles, nonempty resources/kinds and field allowlists',()=>{const a=load();for(const revision of a.CASH_PROFILES)assert.deepEqual(a.cashAdminPayload('propose',{...input,profileRevisions:[revision]}).profileRevisions,[revision]);for(const extra of [{profileRevisions:['finance.v1']},{profileRevisions:a.CASH_PROFILES},{warehouseIds:[]},{kinds:['cash']},{tenantId:id(9)},{permissions:['shipment.update']}])assert.throws(()=>a.cashAdminPayload('propose',{...input,...extra}));});
test('normalized stable retries survive reload with original ID and content',async()=>{const a=load(),d=io();await a.submitCashAdminIntent('propose','A',{...input,reason:'  '+input.reason+'  '},d);await a.submitCashAdminIntent('propose','A',input,d);assert.equal(d.calls[0].operationId,d.calls[1].operationId);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(a.readCashAdminIntent(d.read()).state,'confirmed');});
test('conflicting replacement content rejects before send',async()=>{const a=load(),d=io();await a.submitCashAdminIntent('propose','A',input,d);await assert.rejects(a.submitCashAdminIntent('propose','A',{...input,warehouseIds:[id(9)]},d));assert.equal(d.calls.length,1);});
test('storage failure and failed readback block network',async()=>{for(const mode of ['throw','readback']){const a=load(),d=io();d.write=()=>{if(mode==='throw')throw Error('Denied')};await assert.rejects(a.submitCashAdminIntent('propose','A',input,d));assert.equal(d.calls.length,0);}});
test('uncertain acknowledgement retains immutable identity/content on explicit retry',async()=>{const a=load(),d=io();d.send=async i=>{d.calls.push(i);throw Error('Lost ack')};await assert.rejects(a.submitCashAdminIntent('propose','A',input,d));assert.equal(a.readCashAdminIntent(d.read()).state,'uncertain');d.send=async i=>{d.calls.push(i);return{proposalId:i.operationId,fingerprint:'a'.repeat(64)}};await a.submitCashAdminIntent('propose','A',null,d);assert.deepEqual(d.calls[0],d.calls[1]);});
test('context switch and late mutation response cannot confirm or replay',async()=>{const a=load(),d=io();d.send=async()=>{d.current=()=>false;return{proposalId:id(1),fingerprint:'a'.repeat(64)}};await assert.rejects(a.submitCashAdminIntent('propose','A',input,d));assert.equal(a.readCashAdminIntent(d.read()).state,'uncertain');d.current=()=>true;await assert.rejects(a.submitCashAdminIntent('propose','B',null,d));});
test('acceptance verifies exact context/resource/profile snapshot and operation',async()=>{const a=load(),d=io(),v={proposalId:id(8),fingerprint:'a'.repeat(64),reason:'Independent',expected:basis},receipt={...basis,companyMembershipId:basis.membershipId,acceptanceId:id(1)};for(const change of [{legalEntityId:id(9)},{companyMembershipId:id(9)},{warehouseIds:[id(9)]},{kinds:['cod']},{profileRevisions:['warehouse-cash.v1']},{acceptanceId:id(9)}]){d.send=async()=>({...receipt,...change});await assert.rejects(a.submitCashAdminIntent('accept','A',v,d));}d.send=async()=>receipt;await a.submitCashAdminIntent('accept','A',null,d);assert.equal(a.readCashAdminIntent(d.read()).state,'confirmed');});
test('revocation receipt must identify exact removed acceptance',async()=>{const a=load(),d=io(),v={membershipId:id(2),legalEntityId:id(3),expectedAcceptanceId:id(4),reason:'Revoke'};d.send=async()=>({companyMembershipId:id(2),revokedAcceptanceId:id(9)});await assert.rejects(a.submitCashAdminIntent('revoke','A',v,d));d.send=async()=>({companyMembershipId:id(2),revokedAcceptanceId:id(4)});await a.submitCashAdminIntent('revoke','A',null,d);});
test('exclusive lock failure causes no persistence/send',async()=>{const a=load(),d=io();d.lock=async()=>{throw Error('Busy tab')};await assert.rejects(a.submitCashAdminIntent('propose','A',input,d));assert.equal(d.read(),null);assert.equal(d.calls.length,0);});
test('operational stale rejection differs from identity conflict; unknown 409 remains uncertain',async()=>{const a=load(),d=io();assert.notEqual(a.cashAdminError({response:{data:{code:'CASH_CAPABILITY_GRANT_STALE'}}}),a.cashAdminError({response:{data:{code:'CASH_CAPABILITY_INTENT_CONFLICT'}}}));d.send=async()=>{throw{response:{status:409,data:{code:'OTHER_ERROR'}}}};await assert.rejects(a.submitCashAdminIntent('propose','A',input,d));assert.equal(a.readCashAdminIntent(d.read()).state,'uncertain');d.send=async()=>{throw{response:{status:409,data:{code:'CASH_CAPABILITY_GRANT_STALE'}}}};await assert.rejects(a.submitCashAdminIntent('propose','A',null,d));assert.equal(a.readCashAdminIntent(d.read()).state,'rejected');});
test('scoped reads strip extra fields and reject stale epoch/foreign context',async()=>{const a=load();a.state.data={revision:'cash-delegation.v1',kind:'proposer',legalEntity:{id:id(3),name:'Synthetic',baseCurrency:'UZS'},profiles:[{revision:'local-driver-cash.v1',permissions:['cash.collect']}],kinds:['service_charge'],warehouses:[{id:id(4),name:'Synthetic'}],tokenHash:'hidden'};assert(!JSON.stringify(await a.readCashAdministration('A','ceiling','proposer')).includes('hidden'));a.state.context='B';await assert.rejects(a.readCashAdministration('A','ceiling','proposer'));a.state.context='A';a.state.wait=new Promise(r=>{a.state.resolve=r});const work=a.readCashAdministration('A','ceiling','proposer');a.state.epoch++;a.state.resolve(a.state.data);await assert.rejects(work);});
