const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const ts=require('typescript');
function load(file,mocks={}){
 const filename=path.join(__dirname,'../lib',file+'.ts'),mod=new Module(filename,module);mod.paths=module.paths;
 mod.require=name=>Object.hasOwn(mocks,name)?mocks[name]:name==='./master-write'?load('master-write'):require(name);
 mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,filename);return mod.exports;
}
const core=load('master-write');
const id='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const input={path:'/api/customers',method:'POST',body:{type:'PERSON',name:'Synthetic',email:null}};
const deferred=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
function harness(){let raw=null,context='tenant/company/member',epoch='epoch-a',sends=0,fail=false;const d={context:()=>context,epoch:()=>epoch,read:()=>raw,write:v=>{if(fail)throw Error('Storage failed');raw=v;},id:()=>id,lock:work=>work(),send:async record=>{sends++;assert.equal(JSON.parse(raw).state,'pending');assert.deepEqual(JSON.parse(raw).body,record.body);return{id};}};return{d,get raw(){return raw},get sends(){return sends},set context(v){context=v},set epoch(v){epoch=v},set fail(v){fail=v}};}
test('persist/read-back precedes send; confirmed record remains until acknowledged',async()=>{const h=harness();assert.deepEqual(await core.executeMasterWrite(input,h.d),{id});assert.equal(h.sends,1);assert.equal(JSON.parse(h.raw).state,'confirmed');await assert.rejects(core.executeMasterWrite(input,h.d),/pending intent/);assert.equal(h.sends,1)});
test('storage failure and failed read-back cause zero network work',async()=>{for(const mode of ['throw','readback']){const h=harness();if(mode==='throw')h.fail=true;else h.d.write=()=>{};await assert.rejects(core.executeMasterWrite(input,h.d));assert.equal(h.sends,0)}});
test('pending intent after restart blocks replay and conflicting new work',async()=>{const h=harness();h.d.write(JSON.stringify({...input,version:1,id,context:h.d.context(),state:'pending'}));await assert.rejects(core.executeMasterWrite({...input,body:{name:'Changed'}},h.d));assert.equal(h.sends,0);assert.equal(JSON.parse(h.raw).body.name,'Synthetic')});
test('timeout is uncertain and no automatic retry is attempted',async()=>{const h=harness();let sends=0;h.d.send=async()=>{sends++;throw Error('Timeout')};await assert.rejects(core.executeMasterWrite(input,h.d));assert.equal(JSON.parse(h.raw).state,'uncertain');await assert.rejects(core.executeMasterWrite(input,h.d));assert.equal(sends,1)});
test('rejected requests retain explicit rejection for review',async()=>{for(const status of [400,401,403,404,409,422]){const h=harness();h.d.send=async()=>{throw{response:{status}}};await assert.rejects(core.executeMasterWrite(input,h.d));assert.equal(JSON.parse(h.raw).state,'rejected')}});
test('late response after context change cannot confirm or overwrite original intent',async()=>{const h=harness(),result=deferred();h.d.send=()=>result.promise;const pending=core.executeMasterWrite(input,h.d);await new Promise(r=>setImmediate(r));h.context='foreign';h.epoch='epoch-b';result.resolve({id});await assert.rejects(pending,/Session changed/);assert.equal(JSON.parse(h.raw).state,'pending');assert.equal(JSON.parse(h.raw).context,'tenant/company/member')});
test('context change while waiting for lock causes zero sends and writes',async()=>{const h=harness(),lock=deferred();h.d.lock=async work=>{await lock.promise;return work()};const pending=core.executeMasterWrite(input,h.d);h.epoch='epoch-b';lock.resolve();await assert.rejects(pending,/Session changed/);assert.equal(h.raw,null);assert.equal(h.sends,0)});
test('intent snapshots content before asynchronous lock admission',async()=>{const h=harness(),lock=deferred(),mutable=structuredClone(input);h.d.lock=async work=>{await lock.promise;return work()};const pending=core.executeMasterWrite(mutable,h.d);mutable.body.name='Changed';lock.resolve();await pending;assert.equal(JSON.parse(h.raw).body.name,'Synthetic')});
test('matching concurrent submissions are serialized and second cannot send',async()=>{const h=harness();let tail=Promise.resolve();h.d.lock=work=>{const next=tail.then(work);tail=next.catch(()=>{});return next};const outcomes=await Promise.allSettled([core.executeMasterWrite(input,h.d),core.executeMasterWrite(input,h.d)]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);assert.equal(h.sends,1)});
test('unknown or corrupt recovery record fails closed',()=>{assert.throws(()=>core.readMasterIntent('{'));assert.throws(()=>core.readMasterIntent(JSON.stringify({version:0})));assert.equal(core.readMasterIntent(null),null)});
function adapter(){let context='a',epoch='a',calls=[],response;const store=new Map();global.window={location:{origin:'http://synthetic.invalid'},localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}};Object.defineProperty(global,'navigator',{configurable:true,value:{locks:{request:async(_key,_opts,work)=>work({})}}});global.crypto=require('node:crypto').webcrypto;const api={defaults:{baseURL:'http://synthetic.invalid'},get:async(p,c)=>{calls.push({p,c});return{data:typeof response==='function'?await response():response}},request:async c=>{calls.push(c);return{data:{id}}}};const value=load('customer-workspace',{'./api':{api},'./auth':{authContext:()=>context,authEpoch:()=>epoch}});return{value,calls,store,set response(v){response=v},set context(v){context=v},set epoch(v){epoch=v}};}
const customer={id,type:'PERSON',name:'Synthetic',createdAt:'2026-10-07T00:00:00Z'};
test('list uses bounded actual contract and removes unneeded response fields',async()=>{const h=adapter();h.response={data:[{...customer,passwordHash:'excluded'}],total:1,page:1,limit:20,pageCount:1};const result=await h.value.listWorkspaceCustomers('a',{q:'test',page:1});assert.equal(h.calls[0].c.params.limit,20);assert.equal(result.data[0].passwordHash,undefined)});
test('address list uses take and requires the exact selected customer',async()=>{const h=adapter();h.response=[{id:other,customerEntityId:id}];await h.value.listWorkspaceAddresses('a',id,'');assert.equal(h.calls[0].c.params.take,50);assert.equal(h.calls[0].c.params.page,undefined);h.response=[{id:other,customerEntityId:other}];await assert.rejects(h.value.listWorkspaceAddresses('a',id,''),/relationship mismatch/)});
test('missing/foreign context cannot query or write',async()=>{const h=adapter();await assert.rejects(h.value.listWorkspaceCustomers('foreign',{q:'',page:1}));await assert.rejects(h.value.writeCustomerWorkspace('',input));assert.equal(h.calls.length,0);assert.equal(h.store.size,0)});
test('late reads cannot surface protected old-context results',async()=>{const h=adapter(),result=deferred();h.response=()=>result.promise;const pending=h.value.readWorkspaceCustomer('a',id);h.epoch='new';result.resolve(customer);await assert.rejects(pending,/Session changed/)});
test('strict write allowlists reject ownership and alternate paths without persistence',async()=>{const h=adapter();for(const change of [{...input,body:{...input.body,tenantId:other}},{...input,path:'https://foreign.invalid/api/customers'},{...input,path:'/api/customers/'+id,method:'PATCH',body:{defaultAddressId:id,companyId:other}}])await assert.rejects(h.value.writeCustomerWorkspace('a',change));assert.equal(h.calls.length,0);assert.equal(h.store.size,0)});
test('actual write adapter sets noReplay, deadline and normalized explicit fields',async()=>{const h=adapter();await h.value.writeCustomerWorkspace('a',input);assert.equal(h.calls.length,1);assert.equal(h.calls[0].noReplay,true);assert.equal(h.calls[0].timeout,15000);assert.equal(h.calls[0].data.tenantId,undefined);assert.equal(h.value.pendingCustomerIntent('a').state,'confirmed');h.value.dismissCustomerIntent('a');assert.equal(h.value.pendingCustomerIntent('a'),null)});
test('uncertain records cannot be dismissed; company context partitions recovery storage',()=>{const h=adapter();const key='cp_customer_intent_v1:'+encodeURIComponent('http://synthetic.invalid')+':a';h.store.set(key,JSON.stringify({...input,id,version:1,context:'a',state:'uncertain'}));assert.throws(()=>h.value.dismissCustomerIntent('a'),/cannot be discarded/);assert.equal(h.value.pendingCustomerIntent('b'),null);assert.equal(h.store.size,1)});
test('unsupported lock API denies write rather than risking concurrent send',async()=>{const h=adapter();global.navigator.locks=undefined;await assert.rejects(h.value.writeCustomerWorkspace('a',input),/serialize/);assert.equal(h.calls.length,0)});
