const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const id='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',warehouse='00000000-0000-4000-8000-000000000003';
function load(name,mocks={}){const file=path.join(__dirname,'../lib',name+'.ts'),m=new Module(file,module);m.paths=module.paths;m.require=x=>Object.hasOwn(mocks,x)?mocks[x]:x.startsWith('./')?load(x.slice(2),mocks):require(x);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports}
const core=load('driver-intent');
const invite={email:' User@Example.invalid ',profileRevision:'local-driver.v1',reason:' Synthetic invitation '};
const receipt={invitationId:other,expiresAt:'2026-10-10T12:00:00.000Z',delivery:'token-returned-once'};
function harness(){const h={raw:null,current:true,calls:[],writes:[]};h.io={current:()=>h.current,read:()=>h.raw,write:s=>{h.raw=s;h.writes.push(s)},uuid:()=>id,lock:async f=>f(),send:async i=>{h.calls.push(i);return{...receipt,token:'S'.repeat(43)}}};return h;}
test('exact driver profiles reject broader authority and scopes',()=>{assert.deepEqual(Object.keys(core.DRIVER_PROFILES),['local-driver.v1','linehaul-driver.v1']);assert.equal(core.driverPayload('invite',invite).email,'user@example.invalid');for(const extra of [{warehouseIds:[id]},{driverType:'local'},{tenantId:id},{permissionKeys:['shipment.view']},{roleCodes:['owner']},{password:'secret'}])assert.throws(()=>core.driverPayload('invite',{...invite,...extra}));});
test('persistence precedes send and stored receipts never include one-time tokens',async()=>{const h=harness();h.io.send=async i=>{assert.equal(JSON.parse(h.raw).state,'pending');h.calls.push(i);return{...receipt,token:'S'.repeat(43)}};const i=await core.submitDriverIntent('invite','owned',invite,h.io);assert.equal(i.state,'confirmed');assert.equal(i.operationId,id);assert.equal(h.raw.includes('SSSS'),false);assert.equal(h.raw.includes('token"'),false)});
test('storage failure and failed readback prevent network work',async()=>{for(const write of [()=>{throw Error('full')},()=>{}]){const h=harness();h.io.write=write;await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io));assert.equal(h.calls.length,0)}});
test('uncertain retry after restart retains exact ID/content; editing rejects',async()=>{const h=harness();h.io.send=async i=>{h.calls.push(i);throw{response:{status:503}}};await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io));assert.equal(JSON.parse(h.raw).state,'uncertain');const body=h.calls[0];await assert.rejects(core.submitDriverIntent('invite','owned',{...invite,email:'other@example.invalid'},h.io),/Conflicting/);h.io.send=async i=>{assert.deepEqual(i.payload,body.payload);assert.equal(i.operationId,body.operationId);return receipt};await core.submitDriverIntent('invite','owned',null,h.io)});
test('explicit conflict is recorded without replacing the original identity',async()=>{const h=harness();h.io.send=async()=>{throw{response:{status:409,data:{code:'DELEGATION_OPERATION_CONFLICT'}}}};await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io));const i=core.readDriverIntent(h.raw);assert.equal(i.code,'DELEGATION_OPERATION_CONFLICT');assert.equal(i.operationId,id)});
test('context changes before and after network suppress replay and confirmation',async()=>{const h=harness();h.current=false;await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io));assert.equal(h.calls.length,0);h.current=true;h.io.send=async()=>{h.current=false;return receipt};await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io),/Session changed/);assert.equal(JSON.parse(h.raw).state,'pending')});
test('cross-tab lock denial produces no send or intent',async()=>{const h=harness();h.io.lock=async()=>{throw Error('busy')};await assert.rejects(core.submitDriverIntent('invite','owned',invite,h.io));assert.equal(h.raw,null);assert.equal(h.calls.length,0)});
test('recovered intents reject injected secret fields and malformed receipt',()=>{for(const payload of [{...invite,token:'S'.repeat(43)},{...invite,password:'secret'}])assert.throws(()=>core.readDriverIntent(JSON.stringify({version:1,kind:'invite',context:'owned',operationId:id,payload,state:'pending'})));assert.throws(()=>core.readDriverIntent(JSON.stringify({version:1,kind:'invite',context:'owned',operationId:id,payload:core.driverPayload('invite',invite),state:'confirmed'})))});
test('safe errors never echo token, password, request body or arbitrary server text',()=>{assert.equal(core.driverError({response:{data:{error:'secret',code:'DELEGATION_SECRET_REJECTED'}},config:{data:'secret'}}).includes('secret'),false);for(const code of ['INVITATION_UNAVAILABLE','INVITATION_ALREADY_USED','INVITATION_IDENTITY_REQUIRED','DELEGATION_SCOPE_CEILING'])assert.ok(core.driverError({response:{data:{code}}}).length>20)});
function adapter(){let selected='owned',epoch='epoch';const store=new Map(),calls=[];const api={defaults:{baseURL:'http://127.0.0.1:4000'},post:async(...args)=>{calls.push({kind:'bound',args});return{data:receipt}}},anon={post:async(...args)=>{calls.push({kind:'anonymous',args});return{data:{companyMembershipId:id,tenantId:other,companyId:warehouse,tenantMembershipId:id,userId:other,profileRevision:"local-driver.v1"}}}};
global.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};Object.defineProperty(global,'navigator',{value:{locks:{request:async(k,o,f)=>f({name:k})}},configurable:true});global.window={location:{origin:'http://127.0.0.1:3000'}};
const m=load('driver-workspace',{'./api':{api},'./auth':{authContext:()=>selected,authEpoch:()=>epoch,getUser:()=>({id:other})},axios:{create:()=>anon}});return{m,store,calls,api,anon,set context(v){selected=v},set epoch(v){epoch=v}};}
test('invitation/cancel/grant route contracts use noReplay and immutable UUIDs',async()=>{const a=adapter();await a.m.mutateDriver('owned','invite',invite);assert.equal(a.calls[0].args[0],'/api/auth/company-driver-invitations');assert.equal(a.calls[0].args[2].noReplay,true);a.api.post=async(...args)=>{a.calls.push({args});return{data:{invitationId:other,state:'cancelled'}}};await a.m.mutateDriver('owned','cancel',{invitationId:other,reason:'cancel'});assert.equal(a.calls[1].args[0],'/api/auth/company-driver-invitations/cancel');a.api.post=async(...args)=>{a.calls.push({args});return{data:{companyMembershipId:other,action:'revoke',profileRevision:'local-driver.v1'}}};await a.m.mutateDriver('owned','grant',{membershipId:other,action:'revoke',profileRevision:'local-driver.v1',reason:'revoke'});assert.equal(a.calls[2].args[0],'/api/auth/company-driver-grants')});
test('acceptance new credentials are transient; no auth header or secrets persisted',async()=>{const a=adapter();a.context=null;await a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'Synthetic-only-password!'});assert.equal(a.calls[0].kind,'anonymous');assert.equal(a.calls[0].args[1].password,'Synthetic-only-password!');for(const raw of a.store.values()){assert.equal(raw.includes('SSSS'),false);assert.equal(raw.includes('Synthetic-only-password'),false);assert.equal(raw.includes('"password"'),false);assert.equal(raw.includes('"token"'),false)}});
test('existing acceptance sends authenticated token intent without credentials or identity selector',async()=>{const a=adapter();a.api.post=async(...args)=>{a.calls.push({kind:'bound',args});return{data:{companyMembershipId:id,tenantId:other,companyId:warehouse,tenantMembershipId:id,userId:other,profileRevision:"local-driver.v1"}}};await a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'existing'});assert.equal(a.calls[0].kind,'bound');assert.deepEqual(Object.keys(a.calls[0].args[1]).sort(),['operationId','token']);assert.equal(a.calls[0].args[2].noReplay,true);await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'existing',password:'forbidden'}))});
test('uncertain new acceptance blocks credential replay; signed-in confirmation retains ID',async()=>{const a=adapter();a.context=null;a.anon.post=async(...args)=>{a.calls.push({kind:'anonymous',args});throw Error('lost')};await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'Synthetic-only-password!'}));const original=a.calls[0].args[1].operationId;await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'Synthetic-only-password!'}),/Sign in/);assert.equal(a.calls.length,1);a.context='owned';a.api.post=async(...args)=>{a.calls.push({kind:'bound',args});return{data:{companyMembershipId:id,tenantId:other,companyId:warehouse,tenantMembershipId:id,userId:other,profileRevision:"local-driver.v1"}}};await a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'existing'});assert.equal(a.calls[1].args[1].operationId,original);assert.equal('password' in a.calls[1].args[1],false)});
test('missing identity, invalid token and overlong UTF-8 credentials prevent send',async()=>{const a=adapter();a.context=null;await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'existing'}));await assert.rejects(a.m.acceptDriverInvitation({token:'bad',mode:'new',name:'Synthetic',password:'Synthetic-only-password!'}));await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'界'.repeat(25)}));assert.equal(a.calls.length,0)});
test('uncertain metadata cannot be discarded; confirmed intents allow explicit next action',async()=>{const a=adapter();a.api.post=async()=>{throw Error('lost')};await assert.rejects(a.m.mutateDriver('owned','invite',invite));await assert.rejects(a.m.finishDriver('owned','invite'));a.api.post=async()=>({data:receipt});await a.m.mutateDriver('owned','invite',null);await a.m.finishDriver('owned','invite');assert.equal(a.m.pendingDriver('owned','invite'),null)});
test('mismatched grant or cancellation confirmation stays uncertain',async()=>{for(const [kind,payload,result] of [['cancel',{invitationId:id,reason:'cancel'},{invitationId:other,state:'cancelled'}],['grant',{membershipId:id,action:'grant',profileRevision:'local-driver.v1',reason:'grant'},{companyMembershipId:other,action:'grant',profileRevision:'local-driver.v1'}]]){const h=harness();h.io.send=async()=>result;await assert.rejects(core.submitDriverIntent(kind,'owned',payload,h.io),/mismatch/);assert.equal(JSON.parse(h.raw).state,'uncertain')}});
test('anonymous acceptance respects an existing /api base without double prefix',async()=>{const a=adapter();a.context=null;a.api.defaults.baseURL='/api';await a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'Synthetic-only-password!'});assert.equal(a.calls[0].args[0],'/auth/company-driver-invitations/accept')});
test('a rejected new-user attempt cannot silently replay or change credentials',async()=>{const a=adapter();a.context=null;a.anon.post=async(...args)=>{a.calls.push({args});throw{response:{status:403,data:{code:'INVITATION_UNAVAILABLE'}}}};await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Synthetic',password:'Synthetic-only-password!'}));await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'new',name:'Changed',password:'Changed-password-too!'}),/Sign in/);assert.equal(a.calls.length,1)});
test('mismatched existing identity confirmation cannot become a confirmed receipt',async()=>{const a=adapter();a.api.post=async()=>({data:{companyMembershipId:id,tenantId:other,companyId:warehouse,tenantMembershipId:id,userId:id,profileRevision:"local-driver.v1"}});await assert.rejects(a.m.acceptDriverInvitation({token:'S'.repeat(43),mode:'existing'}),/mismatch/);assert.equal([...a.store.values()].some(s=>JSON.parse(s).state==='confirmed'),false)});
test('finishing a confirmed receipt uses the submission lock and cannot erase a competing retry',async()=>{const a=adapter();await a.m.mutateDriver('owned','invite',invite);const before=[...a.store.entries()];let lockKey;global.navigator.locks.request=async(k,o,f)=>{lockKey=k;assert.equal(o.ifAvailable,true);return f(null)};await assert.rejects(a.m.finishDriver('owned','invite'),/Another tab/);assert.deepEqual([...a.store.entries()],before);assert.ok(lockKey.endsWith(':owned:invite'));global.navigator.locks.request=async(k,o,f)=>{assert.equal(k,lockKey);return f({name:k})};await a.m.finishDriver('owned','invite');assert.equal(a.m.pendingDriver('owned','invite'),null)});
