/* eslint-disable @typescript-eslint/no-require-imports -- Installed Node CommonJS test loader, not application imports. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const config={baseCurrency:'UZS',fiscalYearStartMonth:4,timezone:'Asia/Tashkent',reportingCurrency:null};
const input={configuration:config,reason:'Explicit synthetic configuration'};
function compile(file,requireFn){const m=new Module(file,module);m.paths=module.paths;if(requireFn)m.require=requireFn;m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function load(){const state={context:'A',epoch:1,calls:[],data:null};return {...compile(path.join(__dirname,'../lib/entity-setup.ts'),p=>p==='./api'?{api:{get:async(...v)=>{state.calls.push(v);return{data:state.wait?await state.wait:state.data}}}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?compile(path.join(__dirname,'../lib/creation-intent.ts')):require(p)),state};}
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id(1),lock:async f=>f(),calls:[],send:async i=>{assert.equal(JSON.parse(raw).operationId,i.operationId);d.calls.push(i);return{proposalId:id(1),contentHash:'a'.repeat(64)}}};return d;}
test('explicit month/timezone/currency, null reporting and ownership allowlists',()=>{const a=load();assert.deepEqual(a.setupPayload('propose',input),input);for(const configuration of [{...config,fiscalYearStartMonth:0},{...config,timezone:'Fake/Zone'},{...config,timezone:'+01:00'},{...config,baseCurrency:''},{...config,reportingCurrency:'USD'}])assert.throws(()=>a.setupPayload('propose',{...input,configuration}));for(const k of ['tenantId','companyId','settings'])assert.throws(()=>a.setupPayload('propose',{...input,[k]:id(9)}));});
test('missing configuration values never obtain defaults',()=>{const a=load();for(const k of Object.keys(config)){const c={...config};delete c[k];assert.throws(()=>a.setupPayload('propose',{...input,configuration:c}));}});
test('normalized identical retry after restart preserves operation and payload',async()=>{const a=load(),d=io();await a.submitSetupIntent('propose','A',{...input,reason:'  Explicit synthetic configuration  '},d);await a.submitSetupIntent('propose','A',input,d);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(d.calls[0].operationId,d.calls[1].operationId);assert.equal(a.readSetupIntent(d.read()).state,'confirmed');});
test('conflicting retry rejects before send',async()=>{const a=load(),d=io();await a.submitSetupIntent('propose','A',input,d);await assert.rejects(a.submitSetupIntent('propose','A',{...input,configuration:{...config,baseCurrency:'USD'}},d));assert.equal(d.calls.length,1);});
test('storage error or failed read-back cannot send',async()=>{for(const mode of ['error','readback']){const a=load(),d=io();d.write=()=>{if(mode==='error')throw Error('Denied')};await assert.rejects(a.submitSetupIntent('propose','A',input,d));assert.equal(d.calls.length,0);}});
test('late response after context change cannot confirm previous intent',async()=>{const a=load(),d=io();d.send=async()=>{d.current=()=>false;return{proposalId:id(1),contentHash:'a'.repeat(64)}};await assert.rejects(a.submitSetupIntent('propose','A',input,d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('uncertain request keeps original ID/config across explicit retry',async()=>{const a=load(),d=io();d.send=async i=>{d.calls.push(i);throw Error('Lost acknowledgement')};await assert.rejects(a.submitSetupIntent('propose','A',input,d));const old=d.read();d.send=async i=>{d.calls.push(i);return{proposalId:i.operationId,contentHash:'a'.repeat(64)}};await a.submitSetupIntent('propose','A',null,d);assert.equal(d.calls[0].operationId,JSON.parse(old).operationId);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);});
test('foreign saved intent cannot send',async()=>{const a=load(),d=io();await a.submitSetupIntent('propose','A',input,d);await assert.rejects(a.submitSetupIntent('propose','B',null,d));assert.equal(d.calls.length,1);});
test('decision receipt validates exact snapshot, decision and publication',async()=>{const a=load(),d=io(),v={proposalId:id(2),contentHash:'b'.repeat(64),decision:'approved',reason:'Independent review',expected:config};d.send=async()=>({proposalId:id(2),contentHash:v.contentHash,decision:'approved',legalEntityId:id(3),configuration:{...config,fiscalYearStartMonth:1}});await assert.rejects(a.submitSetupIntent('decide','A',v,d));assert.equal(JSON.parse(d.read()).state,'uncertain');d.send=async()=>({proposalId:id(2),contentHash:v.contentHash,decision:'approved',legalEntityId:id(3),configuration:config});await a.submitSetupIntent('decide','A',null,d);assert.equal(JSON.parse(d.read()).state,'confirmed');});
test('operational conflict is distinct from intent conflict',()=>{const a=load();assert.notEqual(a.setupError({response:{data:{code:'ENTITY_SETUP_ALREADY_CONFIGURED'}}}),a.setupError({response:{data:{code:'ENTITY_SETUP_INTENT_CONFLICT'}}}));});
test('reads strip secrets and stale/context-mismatched responses reject',async()=>{const a=load();a.state.data={revision:'issuing-entity-setup.v1',kind:'proposer',companyName:'Synthetic',supportedCurrencies:['UZS','USD','CNY'],reportingCurrency:null,entity:null,passwordHash:'hidden'};assert(!JSON.stringify(await a.readSetup('A','authority','proposer')).includes('hidden'));a.state.context='B';await assert.rejects(a.readSetup('A','authority','proposer'));a.state.context='A';a.state.wait=new Promise(resolve=>{a.state.resolve=resolve});const promise=a.readSetup('A','authority','proposer');a.state.epoch++;a.state.resolve(a.state.data);await assert.rejects(promise);});
test('concurrent send requires exclusive browser lock; rejected lock creates no intent',async()=>{const a=load(),d=io();d.lock=async()=>{throw Error('Another tab')};await assert.rejects(a.submitSetupIntent('propose','A',input,d));assert.equal(d.read(),null);assert.equal(d.calls.length,0);});
