const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const input={membershipId:id(2),legalEntityId:id(3),profileRevisions:['pricing-maker.v1'],expectedAcceptanceId:null,reason:'Synthetic exact proposal'};
function load(){const state={context:'A',epoch:1,calls:[],data:null};const file=path.join(__dirname,'../lib/financial-access.ts'),m=new Module(file,module);m.paths=module.paths;m.require=p=>p==='./api'?{api:{get:async(...v)=>{state.calls.push(v);return{data:state.wait?await state.wait:state.data}}}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?actualCanonical():require(p);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return{...m.exports,state};}
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id(1),lock:async f=>f(),calls:[],send:async i=>{d.calls.push(i);assert.equal(JSON.parse(raw).operationId,i.operationId);return{proposalId:id(1),fingerprint:'a'.repeat(64)};}};return d;}
test('exact six profiles; arbitrary permissions/ownership/duplicates reject',()=>{const a=load();assert.equal(a.FINANCIAL_PROFILES.length,6);for(const p of [{profileRevisions:['cash-driver.v1']},{profileRevisions:['pricing-maker.v1','pricing-maker.v1']},{tenantId:id(9)},{permissions:['*']}])assert.throws(()=>a.financialPayload('propose',{...input,...p}));});
test('normalized profile order yields stable matching retry after restart',async()=>{const a=load(),d=io();await a.submitFinancialIntent('propose','A',{...input,profileRevisions:['pricing-maker.v1','pricing-checker.v1']},d);await a.submitFinancialIntent('propose','A',{...input,profileRevisions:['pricing-checker.v1','pricing-maker.v1']},d);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(d.calls[0].operationId,d.calls[1].operationId);});
test('conflicting content never sends',async()=>{const a=load(),d=io();await a.submitFinancialIntent('propose','A',input,d);await assert.rejects(a.submitFinancialIntent('propose','A',{...input,legalEntityId:id(9)},d));assert.equal(d.calls.length,1);});
test('storage failure/readback prevents send',async()=>{for(const bad of ['write','readback']){const a=load(),d=io();d.write=()=>{if(bad==='write')throw Error('Unavailable')};await assert.rejects(a.submitFinancialIntent('propose','A',input,d));assert.equal(d.calls.length,0);}});
test('late context cannot confirm or rewrite original intent',async()=>{const a=load(),d=io();d.send=async()=>{d.current=()=>false;return{proposalId:id(1),fingerprint:'a'.repeat(64)}};await assert.rejects(a.submitFinancialIntent('propose','A',input,d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('uncertain outcome retains exact payload/ID; explicit matching retry',async()=>{const a=load(),d=io();d.send=async i=>{d.calls.push(i);throw Error('Timeout')};await assert.rejects(a.submitFinancialIntent('propose','A',input,d));const raw=JSON.parse(d.read());assert.equal(raw.state,'uncertain');d.send=async i=>{d.calls.push(i);return{proposalId:id(1),fingerprint:'a'.repeat(64)}};await a.submitFinancialIntent('propose','A',null,d);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(d.calls[1].operationId,raw.operationId);});
test('operational 409 distinct from normalized intent conflict',async()=>{const a=load(),d=io();d.send=async()=>{throw{response:{status:409,data:{code:'FINANCIAL_GRANT_STALE'}}}};await assert.rejects(a.submitFinancialIntent('propose','A',input,d));assert.equal(JSON.parse(d.read()).code,'FINANCIAL_GRANT_STALE');assert.notEqual(a.financialError({response:{data:{code:'FINANCIAL_GRANT_STALE'}}}),a.financialError({response:{data:{code:'FINANCIAL_INTENT_CONFLICT'}}}));});
test('acceptance receipt must match immutable inspected grant',async()=>{const a=load(),d=io();d.send=async()=>({companyMembershipId:id(9),legalEntityId:id(3),profileRevisions:['pricing-maker.v1'],roleIds:[id(8)],acceptanceId:id(1)});await assert.rejects(a.submitFinancialIntent('accept','A',{proposalId:id(7),fingerprint:'b'.repeat(64),reason:'Independent review',expected:{membershipId:id(2),legalEntityId:id(3),profileRevisions:['pricing-maker.v1']}},d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('revocation must return exact removed acceptance',async()=>{const a=load(),d=io();d.send=async()=>({companyMembershipId:id(2),revokedAcceptanceId:id(9)});await assert.rejects(a.submitFinancialIntent('revoke','A',{membershipId:id(2),legalEntityId:id(3),expectedAcceptanceId:id(8),reason:'Controlled revoke'},d));});
test('fresh reads strip secrets; missing context and late responses fail closed',async()=>{const a=load();a.state.data={items:[{membershipId:id(2),name:'Synthetic target',expectedAcceptanceId:null,currentProfiles:[],currentEnabled:false,passwordHash:'hidden'}],nextCursor:null};const r=await a.readFinancialDiscovery('A','recipients','proposer');assert(!JSON.stringify(r).includes('hidden'));a.state.context='B';await assert.rejects(a.readFinancialDiscovery('A','recipients','proposer'));a.state.context='A';a.state.wait=new Promise(resolve=>{a.state.resolve=resolve});const pending=a.readFinancialDiscovery('A','recipients','proposer');a.state.epoch++;a.state.resolve({items:[],nextCursor:null});await assert.rejects(pending);});

function actualCanonical(){const f=path.join(__dirname,'../lib/creation-intent.ts'),m=new Module(f,module);m.paths=module.paths;m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);return m.exports;}