const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
test('template returns bounded server content; oversized responses and late contexts reject',async()=>{const a=adapters(),m=load('order-workspace',a.mocks);a.result=new Blob(['receiverName,pickupAddress\n']);assert.equal((await m.templateInWorkspace('owned')).size,27);a.result=new Blob(['x'.repeat(1048577)]);await assert.rejects(m.templateInWorkspace('owned'),/Unsupported/);const response=deferred();a.api.get=()=>response.promise;const pending=m.templateInWorkspace('owned');a.epoch='changed';response.resolve({data:new Blob(['safe'])});await assert.rejects(pending,/Session changed/)});
function load(name,mocks={}){const file=path.join(__dirname,'../lib',name+'.ts'),mod=new Module(file,module);mod.paths=module.paths;mod.require=x=>Object.hasOwn(mocks,x)?mocks[x]:x==='./creation-intent'?load('creation-intent'):x==='./orders/service-types'?load('orders/service-types'):require(x);mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return mod.exports;}
const core=load('creation-intent'),feed=load('notification-feed'),id='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const deferred=()=>{let resolve;return{promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
function harness(){let raw=null,context='tenant/company/member',epoch='one',calls=0;const d={context:()=>context,epoch:()=>epoch,read:()=>raw,write:v=>raw=v,uuid:()=>id,lock:work=>work(),send:async intent=>{calls++;assert.equal(JSON.parse(raw).operationId,intent.operationId);assert.equal(JSON.parse(raw).state,'pending');return{orders:[{id}],replayedRows:0,downstreamRecoveryRequired:false};}};return{d,get raw(){return raw},get calls(){return calls},set context(v){context=v},set epoch(v){epoch=v}};}
test('persist normalized immutable intent before send; explicit matching retry preserves identity',async()=>{const h=harness();const first=await core.submitCreationIntent('order',{b:2,a:1},h.d);const retry=await core.submitCreationIntent('order',{a:1,b:2},h.d);assert.equal(first.operationId,retry.operationId);assert.equal(h.calls,2)});
test('changed content conflicts without send or replacement',async()=>{const h=harness();await core.submitCreationIntent('order',{a:1},h.d);const saved=h.raw;await assert.rejects(core.submitCreationIntent('order',{a:2},h.d),/Conflicting/);assert.equal(h.raw,saved);assert.equal(h.calls,1)});
test('storage failure and failed readback prevent network',async()=>{for(const failure of ['throw','readback']){const h=harness();h.d.write=failure==='throw'?()=>{throw Error('storage')}:()=>{};await assert.rejects(core.submitCreationIntent('order',{a:1},h.d));assert.equal(h.calls,0)}});
test('unknown result survives restart; retry uses original complete ordered CSV',async()=>{const h=harness(),original={csvText:'a,b\n1,2\n3,4',customerEntityId:id};h.d.send=async()=>{throw Error('Timeout')};await assert.rejects(core.submitCreationIntent('import',original,h.d));assert.equal(JSON.parse(h.raw).state,'uncertain');let got;h.d.send=async i=>{got=i;return{orders:[{id},{id:other}],replayedRows:1,downstreamRecoveryRequired:true}};const r=await core.submitCreationIntent('import',null,h.d);assert.deepEqual(got.payload,original);assert.equal(got.operationId,id);assert.equal(r.orders.length,2);assert.equal(r.replayedRows,1);assert.equal(r.downstreamRecoveryRequired,true)});
test('409 conflict remains blocked and cannot receive new UUID',async()=>{const h=harness();h.d.send=async()=>{throw {response:{status:409}}};await assert.rejects(core.submitCreationIntent('order',{a:1},h.d));assert.equal(JSON.parse(h.raw).state,'conflict');await assert.rejects(core.submitCreationIntent('order',null,h.d),/Conflicting/)});
test('foreign context and same-context new epoch suppress late confirmation',async()=>{for(const change of ['context','epoch']){const h=harness(),r=deferred();h.d.send=()=>r.promise;const p=core.submitCreationIntent('order',{a:1},h.d);await new Promise(r=>setImmediate(r));h[change]='changed';r.resolve({orders:[{id}]});await assert.rejects(p,/Session changed/);assert.equal(JSON.parse(h.raw).state,'pending')}});
test('stored foreign identity, missing context and absent retry all reject without send',async()=>{const h=harness();await assert.rejects(core.submitCreationIntent('order',null,h.d));h.context='';await assert.rejects(core.submitCreationIntent('order',{a:1},h.d));assert.equal(h.calls,0)});
test('input is snapshotted before lock; edits cannot mutate accepted intent',async()=>{const h=harness(),wait=deferred(),payload={a:{value:'original'}};h.d.lock=async work=>{await wait.promise;return work()};const p=core.submitCreationIntent('order',payload,h.d);payload.a.value='changed';wait.resolve();await p;assert.equal(JSON.parse(h.raw).payload.a.value,'original')});
test('busy cross-tab lock rejects before writes',async()=>{const h=harness();h.d.lock=()=>{throw Error('another tab')};await assert.rejects(core.submitCreationIntent('order',{a:1},h.d));assert.equal(h.raw,null);assert.equal(h.calls,0)});
test('oversized or malformed persisted intent fails closed',()=>{assert.throws(()=>core.readCreationIntent('x'.repeat(2000001)));assert.throws(()=>core.readCreationIntent('{'));assert.throws(()=>core.readCreationIntent(JSON.stringify({version:1,kind:'arbitrary'})))});
function adapters(){let context='owned',epoch='one',result={},calls=[];const api={defaults:{baseURL:'https://synthetic.invalid'},post:async(...args)=>{calls.push(args);return{data:result}},get:async(...args)=>{calls.push(args);return{data:result}},request:async options=>{calls.push(options);return{data:result}}};const mocks={'./api':{api},'./auth':{authContext:()=>context,authEpoch:()=>epoch}};return{api,mocks,set result(v){result=v},set context(v){context=v},set epoch(v){epoch=v},calls};}
const orderPayload={customerEntityId:null,sender:{name:'Synthetic',phone:''},receiver:{name:'Receiver',phone:''},addresses:{pickupAddress:'Owned pickup',dropoffAddress:'Owned destination',destinationCity:'Tashkent',senderAddressId:null,receiverAddressId:null},shipment:{serviceType:'DOOR_TO_DOOR',weightKg:1,pieceTotal:1,currency:'UZS',codEnabled:false},reference:{referenceId:'TEST'},note:''};
test('strict order projection accepts free text and owned IDs; rejects financial/ownership and wrong address context',()=>{const a=adapters(),m=load('order-workspace',a.mocks);assert.deepEqual(m.normalOrderInput.parse(orderPayload),orderPayload);for(const field of ['tenantId','ownerOrgId','amount','paid'])assert.throws(()=>m.normalOrderInput.parse({...orderPayload,[field]:'forged'}));assert.throws(()=>m.normalOrderInput.parse({...orderPayload,addresses:{...orderPayload.addresses,senderAddressId:id}}));assert.throws(()=>m.normalOrderInput.parse({...orderPayload,shipment:{...orderPayload.shipment,codEnabled:true}}))});
test('preview uses exact CSV/customer, bounded content and no automatic replay',async()=>{const a=adapters(),m=load('order-workspace',a.mocks);a.result={totalRows:1,validRows:1,invalidRows:0,rows:[{rowNumber:2,valid:true,errors:[],summary:{receiverName:'S',pickupAddress:'P',dropoffAddress:'D',serviceType:'DOOR_TO_DOOR'}}]};await m.previewInWorkspace('owned',{csvText:'a\n1',customerEntityId:id});assert.equal(a.calls[0][0],'/api/orders/import/preview');assert.equal(a.calls[0][2].noReplay,true);await assert.rejects(m.previewInWorkspace('owned',{csvText:'x'.repeat(1048577),customerEntityId:null}));assert.equal(a.calls.length,1)});
test('notification projection uses at/unread, strips private fields and bounds pagination',async()=>{const a=adapters(),m=load('notifications',a.mocks);a.result={items:[{id,type:'order',title:'Synthetic',body:'Owned',at:'2026-10-07T12:00:00.000Z',unread:true,orderId:other,secret:'never'}],hasMore:false,nextCursor:null};const r=await m.fetchUserNotifications({limit:999,cursor:'saved'});assert.equal(r.items[0].secret,undefined);assert.equal(r.items[0].unread,true);assert.equal(a.calls[0].params.limit,50);assert.equal(a.calls[0].params.cursor,'saved')});
test('notification missing context, invalid ID and late response fail closed',async()=>{const a=adapters(),m=load('notifications',a.mocks);a.context='';await assert.rejects(m.fetchUserNotifications());assert.equal(a.calls.length,0);a.context='owned';assert.throws(()=>m.fetchNotification('../foreign'));const result=deferred();a.api.request=()=>result.promise;const p=m.fetchUnreadNotificationCount();a.epoch='changed';result.resolve({data:{unreadCount:1}});await assert.rejects(p,/Session changed/)});
test('read mutations use scoped routes and suppress automatic replay',async()=>{const a=adapters(),m=load('notifications',a.mocks);a.result={success:true,id,readAt:'2026-10-07T12:00:00.000Z'};await m.markNotificationRead(id);assert.equal(a.calls[0].url,`/api/notifications/${id}/read`);assert.equal(a.calls[0].noReplay,true);a.result={success:true,updatedCount:2};await m.markAllNotificationsRead('order');assert.deepEqual(a.calls[1].data,{type:'order'})});
test('realtime only recognizes bounded persisted invalidation signals',()=>{assert.equal(feed.notificationFrame('2'),'ping');assert.equal(feed.notificationFrame('42["driver:notification",{"id":"untrusted"}]'),'invalidate');assert.equal(feed.notificationFrame('42["driver:notifications:unread-count",{}]'),'invalidate');assert.equal(feed.notificationFrame('42["unknown",{}]'),null);assert.equal(feed.notificationFrame('42not-json'),'reject');assert.equal(feed.notificationFrame('x'.repeat(16385)),'reject')});
test('socket reconnect/notification frames refetch; context changes close without delivering',()=>{let current=true,invalidations=0,sent=[],socket={send:s=>sent.push(s),close(){this.onclose?.()},onmessage:null,onclose:null};const stop=feed.connectNotificationFeed({url:'ws://127.0.0.1/socket.io/?EIO=4&transport=websocket',token:()=> 'synthetic',current:()=>current,invalidate:()=>invalidations++,socket:()=>socket});socket.onmessage({data:'0{"sid":"synthetic","pingInterval":25000}'});assert.equal(sent[0],'40{"token":"synthetic"}');socket.onmessage({data:'40{}'});socket.onmessage({data:'42["driver:notification",{}]'});socket.onmessage({data:'42["driver:notification",{}]'});assert.equal(invalidations,3);socket.onmessage({data:'2'});assert.equal(sent[1],'3');current=false;socket.onmessage({data:'42["driver:notification",{}]'});assert.equal(invalidations,3);stop()});
