/* eslint-disable @typescript-eslint/no-require-imports -- Installed CommonJS test loader. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),h='a'.repeat(64);
function compile(file,req){const m=new Module(file,module);m.paths=module.paths;if(req)m.require=req;m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function load(){const state={context:'A',epoch:1};return{...compile(path.join(__dirname,'../lib/pricing-workflow.ts'),p=>p==='./api'?{api:{get:async()=>({data:state.wait?await state.wait:{items:[]}})}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?compile(path.join(__dirname,'../lib/creation-intent.ts')):require(p)),state};}
const payer={orderId:id(2),payerCustomerEntityId:id(3),evidence:'Explicit synthetic payer',reason:'Reviewed intent'};
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id(1),lock:async f=>f(),calls:[],send:async i=>{assert.equal(JSON.parse(raw).operationId,i.operationId);d.calls.push(i);return{id:id(4),payerCustomerEntityId:id(3)}}};return d;}
test('payer/instruction strict inputs exclude ownership, amounts, unsupported methods and omitted timing',()=>{const a=load();assert.deepEqual(a.pricingPayload('payer',payer),payer);for(const field of ['amount','paid','companyId','tenantId'])assert.throws(()=>a.pricingPayload('payer',{...payer,[field]:'x'}));const p={orderId:id(2),billToId:id(4),method:'CASH',collectionParty:'SENDER',evidence:'Explicit',reason:'Explicit'};assert.equal(a.pricingPayload('instruction',p).method,'CASH');for(const v of [{...p,method:'CARD'},{...p,collectionParty:undefined},{...p,collectionParty:'DRIVER'}])assert.throws(()=>a.pricingPayload('instruction',v));});
test('normalized retry after restart retains original ID/content',async()=>{const a=load(),d=io();await a.submitPricingIntent('payer','A',{...payer,reason:'  Reviewed intent  '},d);await a.submitPricingIntent('payer','A',null,d);assert.equal(d.calls[0].operationId,d.calls[1].operationId);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(a.readPricingIntent(d.read()).state,'confirmed');});
test('conflicting edits and foreign stored context reject before network',async()=>{const a=load(),d=io();await a.submitPricingIntent('payer','A',payer,d);await assert.rejects(a.submitPricingIntent('payer','A',{...payer,reason:'Changed'},d));await assert.rejects(a.submitPricingIntent('payer','B',null,d));assert.equal(d.calls.length,1);});
test('persistence failure or failed readback blocks all sending',async()=>{for(const mode of ['throw','readback']){const a=load(),d=io();d.write=()=>{if(mode==='throw')throw Error('Storage failure')};await assert.rejects(a.submitPricingIntent('payer','A',payer,d));assert.equal(d.calls.length,0);}});
test('late response cannot confirm after context or epoch changes',async()=>{const a=load(),d=io();d.send=async()=>{d.current=()=>false;return{id:id(4),payerCustomerEntityId:id(3)}};await assert.rejects(a.submitPricingIntent('payer','A',payer,d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('lost acknowledgement preserves original ID for explicit matching retry',async()=>{const a=load(),d=io();d.send=async i=>{d.calls.push(i);throw Error('Timeout')};await assert.rejects(a.submitPricingIntent('payer','A',payer,d));const first=JSON.parse(d.read());d.send=async i=>{d.calls.push(i);return{id:id(4),payerCustomerEntityId:id(3)}};await a.submitPricingIntent('payer','A',null,d);assert.equal(d.calls[1].operationId,first.operationId);assert.deepEqual(d.calls[1].payload,first.payload);});
test('exclusive lock rejection creates no pending intent or network work',async()=>{const a=load(),d=io();d.lock=async()=>{throw Error('Busy')};await assert.rejects(a.submitPricingIntent('payer','A',payer,d));assert.equal(d.read(),null);assert.equal(d.calls.length,0);});
test('exact receipts bind payer and independent decision without treating 409 as identity conflict',async()=>{const a=load(),d=io();d.send=async()=>({id:id(4),payerCustomerEntityId:id(9)});await assert.rejects(a.submitPricingIntent('payer','A',payer,d));assert.equal(JSON.parse(d.read()).state,'uncertain');const r=a.pricingError({response:{status:409,data:{code:'CASH_BASIS_FROZEN'}}});assert.equal(r,'CASH_BASIS_FROZEN');assert.notEqual(r,a.pricingError({response:{data:{code:'BILLING_INTENT_CONFLICT'}}}));});
test('request contracts strip route references and retain immutable ID for every receipt path',()=>{const a=load();for(const [kind,payload,path] of [['payer',payer,'bill-to'],['instruction',{orderId:id(2),billToId:id(4),method:'CASH',collectionParty:'RECIPIENT',evidence:'explicit',reason:'explicit'},'service-payment-instruction'],['price',{orderId:id(2),reason:'explicit'},'price-acceptance'],['priceApprove',{orderId:id(2),snapshotId:id(4),contentHash:h,reason:'explicit'},'price-approval']]){const r=a.pricingRequest({kind,payload,operationId:id(1)});assert.equal(r.url,'/api/pricing/orders/'+id(2)+'/'+path);assert.equal(r.data.operationId,id(1));assert(!('orderId'in r.data));}});
test('price receipt keeps exact decimal strings and approval state',async()=>{const a=load(),d=io();d.send=async()=>({id:id(4),orderId:id(2),total:'100.0100',currency:'UZS',contentHash:h,state:'approval_required',content:{components:[{amount:'100.01'}]},acceptedAt:null});const r=await a.submitPricingIntent('price','A',{orderId:id(2),reason:'Explicit'},d);assert.equal(r.result.total,'100.0100');assert.equal(r.result.state,'approval_required');});
test('draft writes cannot be replayed even after restart or ambiguous response',async()=>{const a=load(),d=io(),draft={name:'Synthetic',code:null,description:null,status:'draft',serviceType:'DOOR_TO_DOOR',priceType:'bucket',pricingStrategy:'FIXED_LANE',coverageType:'domestic',transportMode:'ROAD',originCountryCode:null,destinationCountryCode:null,routeTemplateId:null,currency:'UZS',priority:1,isDefault:false,customerEntityId:null,rates:[{zone:0,weightFromKg:0,weightToKg:10,price:100}],transitLegRates:[]};d.send=async i=>{d.calls.push(i);throw Error('Lost')};await assert.rejects(a.submitPricingIntent('draftCreate','A',{draft},d));await assert.rejects(a.submitPricingIntent('draftCreate','A',null,d));assert.equal(d.calls.length,1);assert.equal(a.tariffDraft.parse(draft).rates[0].zone,0);});
test('read response after context/epoch switch is suppressed',async()=>{const a=load();a.state.wait=new Promise(r=>a.state.resolve=r);const p=a.readPricing('A','/workflow',{view:'orders'});a.state.epoch++;a.state.resolve({items:[]});await assert.rejects(p);});
test('tariff version and policy decision routes preserve exact generation/fingerprint',()=>{const a=load();const r=a.pricingRequest({kind:'tariffDecide',operationId:id(1),payload:{planId:id(2),versionId:id(3),contentSha256:h,decision:'rejected',reason:'Independent reason'}});assert.equal(r.url,'/api/pricing/tariff-plans/'+id(2)+'/versions/'+id(3)+'/decision');assert.deepEqual(r.data,{contentSha256:h,decision:'rejected',reason:'Independent reason',operationId:id(1)});const p=a.pricingRequest({kind:'policyDecide',operationId:id(1),payload:{versionId:id(2),contentHash:h,decision:'approved',reason:'Independent reason'}});assert.equal(p.data.versionId,id(2));assert.equal(p.data.contentHash,h);});
test('draft deletion confirms only the actual deleted/id backend contract',async()=>{const a=load(),d=io();d.send=async()=>({deleted:true,id:id(2),name:'Synthetic',cleanup:{ratesDeleted:1}});const r=await a.submitPricingIntent('draftDelete','A',{planId:id(2)},d);assert.deepEqual(r.result,{deleted:true,id:id(2)});});
test('immutable proposal receipts require hash and revision, not placeholder success',async()=>{const a=load(),d=io();d.send=async()=>({id:id(3),planId:id(2),sourceGeneration:0});await assert.rejects(a.submitPricingIntent('tariffPropose','A',{planId:id(2),expectedGeneration:0,reason:'Explicit'},d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('explicit policy retains country-qualified zone zero, exact long decimals, states and no implicit tax/defaults',()=>{const a=load(),p={currency:'UZS',precision:2,rounding:'HALF_UP',weight:{source:'recorded_order_kg',rule:'as_recorded'},zones:{source:'structured_address_cities',mappings:[{origin:'A',destination:'B',originCountry:'ZZ',destinationCountry:'ZZ',zone:0,coverageType:'domestic',transportMode:'ROAD'}]},tariff:{strategy:'FIXED_LANE',priceType:'bucket',includedServices:['base']},fees:[{service:'handling',amount:'0.00000000000001'}],discounts:[],tax:{treatment:'not_applicable',authorityReference:'SYNTHETIC EXPLICIT'},calculationOrder:'discount_then_tax',roundingStage:'each_component',billing:{mode:'manual',eligibleOrderStates:['exception','return_in_progress','delivered'],dueDays:7,numberPrefix:'SYN'}};assert.deepEqual(a.policyContent.parse(p),p);for(const k of ['currency','precision','tax','fees','discounts']){const copy={...p};delete copy[k];assert.throws(()=>a.policyContent.parse(copy));}});
