/* eslint-disable @typescript-eslint/no-require-imports -- Installed offline CommonJS test loader. */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'),ctx=JSON.stringify([id(1),id(2),id(3),id(4),id(5)]);
function compile(file,req){const m=new Module(file,module);m.paths=module.paths;if(req)m.require=req;m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
function load(){const state={context:ctx,epoch:1};return {...compile(path.join(__dirname,'../lib/service-cash.ts'),p=>p==='./api'?{api:{defaults:{baseURL:'synthetic'},get:async()=>({data:state.wait?await state.wait:{items:[]}})}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?compile(path.join(__dirname,'../lib/creation-intent.ts')):require(p)),state};}
const collect={orderId:id(6),kind:'service_charge',obligationId:id(7),note:null};
const receipt=(action='collect',extra={})=>({success:true,order:{orderId:id(6),orderNumber:'SYNTHETIC',obligationId:id(7),kind:'service_charge',action,amount:'100.0100',currency:'UZS',expectedEventId:id(8),offerId:null,state:'held',holderMembershipId:id(5),holderWarehouseId:null,sourceWarehouseId:null,...extra}});
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id(10),lock:async f=>f(),calls:[],send:async i=>{assert.equal(JSON.parse(raw).state,'uncertain');assert.equal(JSON.parse(raw).operationId,i.operationId);d.calls.push(i);return receipt()}};return d;}
test('strict mutation fields preserve obligation identity and reject money, COD and ownership',()=>{const a=load();assert.deepEqual(a.cashPayload('collect',collect),collect);for(const field of ['amount','currency','tenantId','paid','companyId'])assert.throws(()=>a.cashPayload('collect',{...collect,[field]:'x'}));assert.throws(()=>a.cashPayload('collect',{...collect,kind:'cod'}));assert.throws(()=>a.cashPayload('collect',{...collect,obligationId:undefined}));});
test('restart and matching retry retain original normalized payload and ID',async()=>{const a=load(),d=io();await a.submitCashIntent(ctx,'collect',collect,d);const original=d.read();await load().submitCashIntent(ctx,'collect',null,d);assert.deepEqual(a.cashRequest(d.calls[0]),a.cashRequest(d.calls[1]));assert.equal(d.read(),original);});
test('different content, order, action or context cannot retarget an unresolved intent',async()=>{const a=load(),d=io();d.send=async()=>{throw Error('Ambiguous')};await assert.rejects(a.submitCashIntent(ctx,'collect',collect,d));const raw=d.read();for(const [context,action,p] of [[ctx,'collect',{...collect,orderId:id(20)}],[ctx,'collect',{...collect,obligationId:id(20)}],[ctx,'offer',null],['other','collect',null]])await assert.rejects(a.submitCashIntent(context,action,p,d));assert.equal(d.read(),raw);});
test('storage throw and failed readback prevent all sending',async()=>{for(const mode of ['throw','readback']){const a=load(),d=io();d.write=()=>{if(mode==='throw')throw Error('Storage unavailable')};await assert.rejects(a.submitCashIntent(ctx,'collect',collect,d));assert.equal(d.calls.length,0);}});
test('exclusive-lock failure prevents persistence and sending',async()=>{const a=load(),d=io();d.lock=async()=>{throw Error('Other tab')};await assert.rejects(a.submitCashIntent(ctx,'collect',collect,d));assert.equal(d.read(),null);assert.equal(d.calls.length,0);});
test('late response after identity/context or session epoch changes stays uncertain',async()=>{for(const mode of ['identity','epoch']){const a=load(),d=io(),session={context:ctx,epoch:1};d.current=()=>session.context===ctx&&session.epoch===1;d.send=async()=>{if(mode==='identity')session.context='foreign';else session.epoch++;return receipt()};await assert.rejects(a.submitCashIntent(ctx,'collect',collect,d));assert.equal(JSON.parse(d.read()).state,'uncertain');}});
test('lost acknowledgement never allocates another ID; explicit retry recovers receipt',async()=>{const a=load(),d=io();d.send=async i=>{d.calls.push(i);throw Error('Timeout')};await assert.rejects(a.submitCashIntent(ctx,'collect',collect,d));const old=d.calls[0];d.uuid=()=>{throw Error('No replacement ID')};d.send=async i=>{d.calls.push(i);return receipt()};await a.submitCashIntent(ctx,'collect',null,d);assert.deepEqual(d.calls[1],old);});
test('offer is confirmed publication only; original holder and event remain until acceptance',async()=>{const a=load(),d=io(),p={orderId:id(6),kind:'service_charge',expectedEventId:id(8),recipientMembershipId:id(11),recipientWarehouseId:id(12)};d.send=async()=>receipt('offer',{offerId:id(13),state:'offered'});const r=await a.submitCashIntent(ctx,'offer',p,d);assert.equal(r.result.holderMembershipId,id(5));assert.equal(r.result.expectedEventId,p.expectedEventId);assert.equal(r.payload.recipientMembershipId,p.recipientMembershipId);d.send=async()=>receipt('offer',{offerId:id(13),state:'held',holderMembershipId:id(11)});await assert.rejects(a.submitCashIntent(ctx,'offer',null,d));});
test('acceptance binds exact offer and current recipient membership; wrong receipt stays uncertain',async()=>{const a=load(),d=io(),p={orderId:id(6),kind:'service_charge',expectedEventId:id(8),offerId:id(13)};d.send=async()=>receipt('accept',{offerId:id(13),expectedEventId:id(14),holderWarehouseId:id(12)});assert.equal((await a.submitCashIntent(ctx,'accept',p,d)).result.holderMembershipId,id(5));d.send=async()=>receipt('accept',{offerId:id(20)});await assert.rejects(a.submitCashIntent(ctx,'accept',null,d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('settlement clears holder and preserves exact decimal strings without financial arithmetic',async()=>{const a=load(),d=io();d.send=async()=>receipt('settle',{state:'settled',holderMembershipId:null,amount:'999999999999.0100'});const r=await a.submitCashIntent(ctx,'settle',{orderId:id(6),kind:'service_charge',expectedEventId:id(8)},d);assert.equal(r.result.amount,'999999999999.0100');});
test('routes strip only orderId and retain immutable event/offer/recipient/null warehouse identity',()=>{const a=load();for(const [action,p,end] of [['collect',collect,'collect'],['offer',{orderId:id(6),kind:'service_charge',expectedEventId:id(8),recipientMembershipId:id(11),recipientWarehouseId:null},'handoff'],['accept',{orderId:id(6),kind:'service_charge',expectedEventId:id(8),offerId:id(13)},'handoff/accept'],['settle',{orderId:id(6),kind:'service_charge',expectedEventId:id(8)},'settle']]){const r=a.cashRequest({action,payload:p,operationId:id(10)});assert.equal(r.url,`/api/orders/${id(6)}/cash/${end}`);assert.equal(r.data.operationId,id(10));assert(!('orderId'in r.data));assert(!('amount'in r.data));}});
test('late discovery response cannot populate another session',async()=>{const a=load();a.state.wait=new Promise(r=>a.state.resolve=r);const p=a.readCash(ctx,'/cash/access');a.state.epoch++;a.state.resolve({items:[]});await assert.rejects(p);});
test('actual error identity distinguishes stale/rejected access from operation conflict',()=>{const a=load();for(const code of ['CASH_OPERATION_CONFLICT','CASH_STATE_STALE','CASH_CAPABILITY_REQUIRED'])assert.equal(a.cashError({response:{data:{error:code}}}),code);});
test('legacy adapter sends nothing and preserves persisted records',async()=>{const a=compile(path.join(__dirname,'../lib/cash.ts'));await assert.rejects(a.mutateCash('collect',[collect]),/Legacy cash submission/);assert(!fs.readFileSync(path.join(__dirname,'../lib/cash.ts'),'utf8').includes('removeItem'));});
test('corrupt, unconfirmed and mismatched persisted receipts cannot become success',()=>{const a=load();assert.throws(()=>a.readCashIntent('{'));assert.throws(()=>a.readCashIntent(JSON.stringify({version:1,context:ctx,action:'collect',operationId:id(10),payload:collect,state:'confirmed'})));assert.throws(()=>a.validateCashReceipt({context:ctx,action:'collect',payload:collect},receipt('collect',{obligationId:id(20)})));});
test('UI affordances separate collection timing, offers, exact recipient and warehouse checker',()=>{const a=load(),cap={membershipId:id(5),profileRevision:'local-driver-cash.v1',permissions:['cash.collect','cash.handoff'],warehouses:[],kinds:['service_charge']},w={...collect,orderStatus:'assigned',collectionParty:'SENDER',amount:'100.0100',expectedEventId:null,state:'preflight-required',holderMembershipId:null,holderWarehouseId:null,offerId:null,recipientMembershipId:null};assert.deepEqual(a.cashAvailableActions(cap,w),['collect']);assert.deepEqual(a.cashAvailableActions(cap,{...w,amount:'0.0000'}),[]);assert.deepEqual(a.cashAvailableActions(cap,{...w,orderStatus:'picked_up'}),[]);assert.deepEqual(a.cashAvailableActions(cap,{...w,collectionParty:'RECIPIENT',orderStatus:'out_for_delivery'}),['collect']);const held={...w,state:'held',expectedEventId:id(8),holderMembershipId:id(5),offerId:id(13),recipientMembershipId:id(11)};assert.deepEqual(a.cashAvailableActions(cap,held),[]);assert.deepEqual(a.cashAvailableActions(cap,{...held,offerId:null}),['offer']);assert.deepEqual(a.cashAvailableActions({...cap,membershipId:id(11)},held),['accept']);assert.deepEqual(a.cashAvailableActions({...cap,membershipId:id(12)},held),[]);assert.deepEqual(a.cashAvailableActions({...cap,permissions:['cash.settle'],profileRevision:'cash-settlement-checker.v1'},held),[]);assert.deepEqual(a.cashAvailableActions({...cap,membershipId:id(20),permissions:['cash.settle'],profileRevision:'cash-settlement-checker.v1'},{...held,holderWarehouseId:id(21)}),['settle']);});
test('actual cash workspace static markup shows exact collection without amount input or generic order authority',()=>{const html=renderCash('local-driver-cash.v1',{orderStatus:'assigned',collectionParty:'SENDER',state:'preflight-required',expectedEventId:null,holderMembershipId:null,offerId:null});assert.match(html,/Record collection/);assert.match(html,/100\.0100 UZS/);assert(!/name="amount"|<input[^>]+type="number"/.test(html));assert.match(html,/Service-charge amount/);assert.match(html,/before picked_up/);});
test('actual cash workspace differentiates original holder offer from exact recipient acceptance',()=>{const holder=renderCash('local-driver-cash.v1',{holderMembershipId:id(5),offerId:id(13),recipientMembershipId:id(11)});assert(!holder.includes('Offer cash handoff'));assert.match(holder,/awaiting acceptance/);assert(!holder.includes('Accept this cash offer'));assert.match(holder,/awaiting acceptance/);const recipient=renderCash('warehouse-cash.v1',{holderMembershipId:id(11),recipientMembershipId:id(5),offerId:id(13)});assert.match(recipient,/Accept this cash offer/);assert(!recipient.includes('Offer cash handoff'));});
test('actual cash workspace pending immutable intent disables new actions and retains original receipt panel',()=>{const html=renderCash('local-driver-cash.v1',{expectedEventId:null,holderMembershipId:null,offerId:null,state:'preflight-required'},true);assert.match(html,/Uncertain original action/);assert.match(html,/Explicitly retry original request/);assert.match(html,/<button[^>]+disabled=""[^>]*>Record collection/);assert(!html.includes('start next action'));});
function renderCash(profile,extra,pending=false){const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');let slot=0;const work={orderId:id(6),orderNumber:'SYNTHETIC',orderStatus:'assigned',obligationId:id(7),collectionParty:'SENDER',kind:'service_charge',amount:'100.0100',currency:'UZS',expectedEventId:id(8),state:'held',holderMembershipId:id(5),holderWarehouseId:null,holderName:'Synthetic driver',holderWarehouseName:null,offerId:null,recipientMembershipId:null,recipientWarehouseId:null,recipientName:'Synthetic warehouse receiver',recipientWarehouseName:'Synthetic owned warehouse',...extra},cap={membershipId:id(5),profileRevision:profile,legalEntityId:id(4),permissions:profile==='cash-settlement-checker.v1'?['cash.custody.read','cash.settle']:['cash.custody.read','cash.collect','cash.handoff'],kinds:['service_charge'],warehouses:[{id:id(12),name:'Synthetic warehouse'}]},page={items:[work],meta:{hasNext:false,nextCursor:null,limit:20}};
 const file=path.join(__dirname,'../components/workspace/ServiceCashWorkspace.tsx'),m=new Module(file,module);m.paths=module.paths;m.require=p=>{
 if(p==='react')return {...React,useEffect:()=>{},useState:value=>React.useState(({1:id(6),2:work.offerId??'',7:pending?{version:1,context:ctx,action:'collect',operationId:id(10),payload:collect,state:'uncertain'}:null,8:true})[slot++]??value)};
 if(p==='@tanstack/react-query')return{useQuery:({queryKey})=>({data:queryKey[0]==='service-cash-access'?cap:queryKey[0]==='service-cash-recipients'?{items:[],meta:{hasNext:false}}:page,isPending:false,isFetching:false,refetch:async()=>{}})};
 if(p==='@/lib/workspace')return {useWorkspaceSession:()=>({user:{id:id(1)},context:ctx,epoch:'1'})};
 if(p==='@/lib/auth')return {authContext:()=>ctx,authEpoch:()=>1};
 if(p==='@/lib/service-cash')return load();
 if(p==='@/components/layout/PageShell')return{__esModule:true,default:({children})=>React.createElement('main',null,children)};
 if(p==='./WorkspaceState')return{__esModule:true,default:({title,description})=>React.createElement('div',null,title,description)};
 if(p==='./PricingWorkflowShared')return {Field:({label,children})=>React.createElement('label',null,label,children),ExactDetails:({value,title})=>React.createElement('details',null,title,React.createElement('pre',null,JSON.stringify(value))),control:'control'};
 if(p==='@/components/ui/button')return {Button:({children,variant,...props})=>{void variant;return React.createElement('button',props,children)}};
 return require(p);
 };m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return renderToStaticMarkup(React.createElement(m.exports.default));}
