const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const id='00000000-0000-4000-8000-000000000001';
const input={name:' Synthetic ',location:' Owned address ',type:'warehouse'};
const result={id,name:'Synthetic',location:'Owned address',type:'warehouse',region:null,latitude:null,longitude:null,createdAt:'2026-10-08T12:00:00.000Z'};
function load(){const state={context:'A',epoch:1,calls:[],response:result};const file=path.join(__dirname,'../lib/warehouse-workspace.ts'),m=new Module(file,module);m.paths=module.paths;m.require=p=>p==='./api'?{api:{get:async(...a)=>{state.calls.push(a);return{data:state.wait?await state.wait:state.response}}}}:p==='./auth'?{authContext:()=>state.context,authEpoch:()=>state.epoch}:p==='./creation-intent'?{canonicalIntent:v=>JSON.stringify(v,Object.keys(v).sort())}:require(p);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return{...m.exports,state};}
function io(){let raw=null;const d={current:()=>true,read:()=>raw,write:v=>raw=v,uuid:()=>id,lock:async f=>f(),calls:[],send:async i=>{d.calls.push(i);assert.equal(JSON.parse(raw).operationId,i.operationId);return result;}};return d;}
test('all supported fields normalize; ownership and invalid coordinates reject',()=>{const a=load();assert.deepEqual(a.warehouseFields.parse(input),{name:'Synthetic',location:'Owned address',type:'warehouse',region:null,latitude:null,longitude:null});for(const x of [{tenantId:id},{users:{}},{latitude:91},{longitude:-181},{latitude:'10'},{type:'unknown'},{name:'a\nprivate'}])assert.throws(()=>a.warehouseFields.parse({...input,...x}));});
test('creation persistence precedes send and matching restart retry retains immutable ID/content',async()=>{const a=load(),d=io();const one=await a.submitWarehouseIntent('create','A',input,d);const two=await a.submitWarehouseIntent('create','A',null,d);assert.equal(one.result.id,two.result.id);assert.deepEqual(d.calls[0].payload,d.calls[1].payload);assert.equal(d.calls.length,2);assert.equal(d.calls[0].operationId,d.calls[1].operationId);});
test('conflicting edits to a creation intent cannot send',async()=>{const a=load(),d=io();await a.submitWarehouseIntent('create','A',input,d);await assert.rejects(a.submitWarehouseIntent('create','A',{...input,name:'different'},d),/immutable/);assert.equal(d.calls.length,1);});
test('write failure and failed readback prevent network work',async()=>{for(const fail of ['write','readback']){const a=load(),d=io();d.write=()=>{if(fail==='write')throw Error('Disk unavailable')};await assert.rejects(a.submitWarehouseIntent('create','A',input,d));assert.equal(d.calls.length,0);}});
test('missing or changed context fails before send',async()=>{const a=load(),d=io();d.current=()=>false;await assert.rejects(a.submitWarehouseIntent('create','A',input,d));assert.equal(d.calls.length,0);});
test('late mutation cannot confirm or rewrite previous context',async()=>{const a=load(),d=io();d.send=async()=>{d.current=()=>false;return result;};await assert.rejects(a.submitWarehouseIntent('create','A',input,d));assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('uncertain creation is retryable with the original identity',async()=>{const a=load(),d=io();d.send=async()=>{throw Error('Timeout')};await assert.rejects(a.submitWarehouseIntent('create','A',input,d));const old=JSON.parse(d.read());d.send=async()=>result;await a.submitWarehouseIntent('create','A',null,d);assert.equal(JSON.parse(d.read()).operationId,old.operationId);});
test('uncertain edit remains blocked after restart and has no replay contract',async()=>{const a=load(),d=io();d.send=async()=>{throw Error('Lost acknowledgement')};await assert.rejects(a.submitWarehouseIntent('edit','A',input,d,id));const original=d.read();d.send=async()=>{throw Error('Must not send')};await assert.rejects(a.submitWarehouseIntent('edit','A',input,d,id),/no server retry/);assert.equal(d.read(),original);});
test('authorized confirmed edit validates its target; wrong confirmation stays uncertain',async()=>{const a=load(),d=io();d.send=async()=>({...result,id:'00000000-0000-4000-8000-000000000002'});await assert.rejects(a.submitWarehouseIntent('edit','A',input,d,id),/mismatch/);assert.equal(JSON.parse(d.read()).state,'uncertain');});
test('read projections strip secrets and enforce bounded selected search',async()=>{const a=load();a.state.response=[{...result,passwordHash:'hidden'}];const rows=await a.readWarehouseWorkspace('A','list',{search:'Synthetic',page:2});assert(!JSON.stringify(rows).includes('hidden'));assert.deepEqual(a.state.calls[0][1].params,{search:'Synthetic',page:2,limit:20});assert.equal(a.state.calls[0][1].noReplay,true);await assert.rejects(a.readWarehouseWorkspace('A','list',{page:10001}));});
test('foreign read and late previous-context response are suppressed',async()=>{const a=load();await assert.rejects(a.readWarehouseWorkspace('B','authority'));assert.equal(a.state.calls.length,0);let resolve;a.state.wait=new Promise(r=>resolve=r);const pending=a.readWarehouseWorkspace('A','list',{});a.state.epoch++;resolve([]);await assert.rejects(pending,/context changed/);});
test('invalid and oversized projections fail closed',async()=>{const a=load();a.state.response=Array(21).fill(result);await assert.rejects(a.readWarehouseWorkspace('A','list',{}));a.state.response={...result,orders:[],users:[{passwordHash:'hidden'}]};await assert.rejects(a.readWarehouseWorkspace('A','detail',{id}));});
